export type dataType = {
    date : Date ,
    subject : string ,
    amount : number ,
    type : string ,
    typeOfType : string ,
    previousMonthAmount : number , 
    profit : number , 
    officeIncome : number ,
    barrowedAmount_1 : number ,
    collectedFromHelp  :number ,
    officeExpence : number ,
    personalExpence  : number ,
    returnBarrowed : number ,
    helpAmount : number ,
    totalExpence : number ,
    helpingAmount : number ,
    collectedAmount : number ,
    balanceWantToCollect : number ,
    barrowedAmount_2  :number ,
    returnedAmount : number ,
    wantToPay : number ,
}